# Generated by Django 5.1.3 on 2025-01-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExcelCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=32)),
                ("company_size", models.CharField(max_length=10)),
                ("region", models.CharField(max_length=64)),
                ("sign_up_date", models.DateField()),
                ("purchase_num", models.IntegerField()),
                ("total_car_price", models.IntegerField()),
                ("churn", models.IntegerField()),
                ("car_model", models.CharField(max_length=32)),
                ("car_price", models.IntegerField()),
                ("score", models.IntegerField()),
                ("mean_score", models.FloatField()),
            ],
            options={
                "db_table": "excel_customer",
            },
        ),
    ]
