# Generated by Django 5.1.4 on 2025-01-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='title',
            new_name='carModel',
        ),
        migrations.RemoveField(
            model_name='board',
            name='content',
        ),
        migrations.AddField(
            model_name='board',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
