# Generated by Django 5.1.4 on 2025-01-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountroletype",
            name="roleType",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("NORMAL", "Normal")],
                default="NORMAL",
                max_length=64,
            ),
        ),
    ]
