# Generated by Django 5.1.3 on 2025-01-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_accountroletype_roletype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountroletype",
            name="roleType",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("NORMAL", "Normal"),
                    ("SUBSCRIBE", "Subscribe"),
                ],
                default="NORMAL",
                max_length=64,
            ),
        ),
    ]
