# Generated by Django 5.1.3 on 2025-01-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rent_car", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentcar",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
